name: Request or unrequest an issue

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  repository-projects: read
  pull-requests: read

jobs:
  request-issue:
    if: github.event.issue.pull_request == null && (startsWith(github.event.comment.body, '/request') || startsWith(github.event.comment.body, '/unrequest'))
    uses: ./.github/workflows/full-sync-issues.yml
    secrets: inherit
